version: '3'

services:
  fastapi:
    build: .
    ports:
      - "8087:8000"
    volumes:
      - .:/app
      - ./sql:/docker-entrypoint-initdb.d
    depends_on:
      db:
        condition: service_healthy  # Esperamos a que db esté saludable antes de iniciar
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpassword@db:3306/superheroes
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    networks:
      - superhero-network
    restart: on-failure
    # Damos tiempo para que la base de datos se inicie completamente
    command: >
      sh -c "
        echo 'Esperando que la base de datos esté lista...' &&
        sleep 10 &&
        python -m uvicorn main:app --host 0.0.0.0 --reload"

  db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: superheroes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - superhero-network
    command: --default-authentication-plugin=mysql_native_password --init-file=/docker-entrypoint-initdb.d/init_superheroes_db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s  # Tiempo inicial para que MySQL se inicie correctamente

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      db:
        condition: service_healthy  # También esperamos a que db esté saludable
    networks:
      - superhero-network

volumes:
  db-data:

networks:
  superhero-network:
    driver: bridge